### ISSUE TITLE
t/output.t fails with non-English locale

### ISSUE THREAD

**Issue by eserte** [brianwisti/MojoX-Date-Local#1]
The test suite fails if a non-English locale is active. For example with `LC_ALL=de_DE.UTF-8`:
```
#   Failed test 'stringified MojoX::Date::Local should include time zone info'
#   at t/output.t line 25.
#          got: 'So, 06 Nov 1994 00:49:37 PST'
#     expected: 'Sun, 06 Nov 1994 00:49:37 PST'

#   Failed test 'stringification extends to sub-seconds if included in epoch'
#   at t/output.t line 32.
#          got: 'So, 06 Nov 1994 00:49:37.123 PST'
#     expected: 'Sun, 06 Nov 1994 00:49:37.123 PST'
# Looks like you failed 2 tests of 4.
t/output.t .. 
```

**Comment by brianwisti** [comment]
Good catch, thank you!

I decided to remove my version of `to_string`, since the output wasn't compliant with RFC-7231. Instead, I added a `format` method that accepts a `POSIX::strftime` format string, defaulting to the sort-of RFC-7231 string I'd been producing before.

The tests themselves should be passing since I'm now just testing that `format` produces the same output as `strftime` given same time and format. Let me know if there are any more test issues!

**Comment by eserte** [comment]
On my smokers there were no failures with 0.04, and the matrix looks greener than before:
http://matrix.cpantesters.org/?dist=MojoX-Date-Local%200.04 . The red spots there seem to be unrelated to locale problems, so I am closing this issue.
